// Licensed to Elasticsearch B.V. under one or more contributor
// license agreements. See the NOTICE file distributed with
// this work for additional information regarding copyright
// ownership. Elasticsearch B.V. licenses this file to you under
// the Apache License, Version 2.0 (the "License"); you may
// not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

// Code generated by beats/dev-tools/cmd/asset/asset.go - DO NOT EDIT.

package tengine

import (
	"github.com/elastic/beats/libbeat/asset"
)

func init() {
	if err := asset.SetFields("metricbeat", "tengine", asset.ModuleFieldsPri, AssetTengine); err != nil {
		panic(err)
	}
}

// AssetTengine returns asset data.
// This is the base64 encoded gzipped contents of ../metricbeat/module/tengine.
func AssetTengine() string {
	return "eJx8jTuOgzAURXuv4oqeDbiYblYxmsIa30EW/sV+KLD7iE8iQCSvvEfvnBY9Jw1h7FykAsSJp0azLY0CLOtfcVlcihpfCgA4ZhYXGMX4n1+1bNsHQrKDn1X/jt5WvcAW0QTuQ8vLlKnRlTTkbbloHUV7WeGtipGhvsiV8q12vSvJObiPcjQhex7YM9tzuqdiT+xDfL7vVbhG1SMAAP//A0Fsjw=="
}
